.TH LEISURE "1" "January 2025" "Jacob Niemeir" "User Commands"
.SH NAME
leisure \- Consolidate media library browsing using fzf
.SH SYNOPSIS
.B leisure

.SH CONFIGURATION
To use leisure, the paths to each media library must be set in preferences.conf.
.br
Due to the number of supported runners, games must be defined in games.csv.
