.TH CP "1" "December 2024" "Jacob Niemeir" "User Commands"
.SH NAME
minServer \- a minimal HTTPS web server
.SH SYNOPSIS
.B minserver [-p \fI\,PORT\/\fR]

.SH DESCRIPTION
.TP
\fB\-h\fR 
display program usage
.TP
\fB\-p[PORT]\fR 
specify port to listen on

.SH COPYRIGHT
Copyright \(co 2024 Jacob Niemeir.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
