.TH CYLLENIAN "1" "December 2024" "Jacob Niemeir" "User Commands"
.SH NAME
Cyllenian \- a minimal HTTPS web server
.SH SYNOPSIS
.B cyllenian [-c \fI\,CERTIFICATE-PATH\/\fR] [-k \fI\,KEY-PATH\/\fR] [-p \fI\,PORT\/\fR]

.SH DESCRIPTION
.TP
\fB\-c[CERTIFICATE-PATH]\fR 
specify path to certificate file
.TP
\fB\-h\fR 
display program usage
.TP
\fB\-k[KEY-PATH]\fR 
specify path to private key file
.TP
\fB\-p[PORT]\fR 
specify port to listen on

.SH COPYRIGHT
Copyright \(co 2024 Jacob Niemeir.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
